# Config for ValkyCraft Crypto Plugin

# GUI settings
gui:
  title: "&6ValkyCraft Crypt GUI"  # Judul GUI dengan kode warna

# Items Configuration
items:
  valid_item:
    material: "DIAMOND"  # Material item yang valid
    custom_model_data: 1  # Custom Model Data untuk item valid
    name: "&bSpecial Diamond"  # Nama item dengan kode warna
    lore:
      - "&7This is a special diamond."
      - "&eUse this item in the crypt."
  submit_button:
    material: "STONE_BUTTON"  # Material untuk tombol submit
    custom_model_data: 0  # Custom Model Data untuk tombol submit
    name: "&aSubmit"  # Nama tombol dengan kode warna
    lore:
      - "&7Click to submit your items."
      - "&eThis will exchange your diamonds for credits."

# Messages Configuration
messages:
  no_diamonds_message: "&cYou need to put diamonds in the slots!"
  submit_success_message: "&aSuccessfully submitted &b%crypt% &7diamond(s)."
  reload_success_message: "&aPlugin reloaded successfully!"
  no_permission_message: "&cYou do not have permission to reload the plugin."
  only_players_message: "&cThis command can only be executed by players."
  invalid_number_message: "&cInvalid number entered. Please provide a valid number."
  diamond_receive_message: "&7You received &b%crypt% &adiamond(s)!"
  only_special_diamond_message: "&cOnly special diamonds can be used in this GUI! Please use the correct item."

# Configuration for Slots
slots:
  valid_item_slots: 11-15  # Slot untuk item yang valid (Diamond)
  submit_button_slot: 16  # Slot untuk tombol submit
