guiTitle: '&6ValkyCraft Crypto'
submitButtonText: '&aSubmit'
noDiamondsMessage: '&cNo diamonds in slots!'
submitSuccessMessage: '&aTransaction successful!'
reloadSuccessMessage: '&aPlugin reloaded!'
noPermissionMessage: '&cYou do not have permission!'
onlyPlayersMessage: '&cThis command can only be run by players.'
invalidNumberMessage: '&cInvalid number specified.'
diamondReceiveMessage: '&aYou received %crypt% %valid_item_name%!'
onlySpecialDiamondMessage: '&cThis is not a valid %valid_item_name%.'

validItem:
  material: 'DIAMOND'
  customModelData: 1
  name: '&bSpecial Crypt Item'
  lore:
    - '&7A special crypt item for ValkyCraft!'
    - '&7Use it wisely.'
