# General GUI Settings
gui:
  title: "&6Valkycraft Crypt" # Title for the GUI window

# Submit Button Settings
items:
  submit_button:
    material: "DIAMOND" # Item type for the submit button
    custom_model_data: 1 # Custom model data for the submit button
    name: "&aSubmit Crypt" # Name for the submit button
    lore:
      - "&7Click to submit your diamonds."
      - "&7Earn money by depositing diamonds!"

  valid_item:
    material: "DIAMOND" # Material for the valid item (can be changed)
    custom_model_data: 1 # Custom model data for the valid item
    name: "&bSpecial Diamond" # Name for the valid item

# Message Settings
messages:
  no_diamonds_message: "&cYou need to add diamonds to the crypt!"
  submit_success_message: "&aYou have submitted &b%crypt% &adiamonds to the crypt!"
  reload_success_message: "&aPlugin configuration reloaded successfully!"
  no_permission_message: "&cYou do not have permission to perform this action."
  only_players_message: "&cThis command can only be used by players."
  invalid_number_message: "&cPlease enter a valid number greater than 0."
  diamond_receive_message: "&aYou received &b%crypt% &adiamonds!"
  only_special_diamond_message: "&cYou can only add special diamonds to the crypt!"

# Permissions (used in the command handler)
permissions:
  give: "valkycraft.give"
  reload: "valkycraft.reload"

# Economy Command Configuration
economy:
  eco_command: "eco give" # Command for adding money to the player's balance (can be changed to other economy plugins)
